In [1]:
import numpy as mp
import pandas as pd
import os
pd.set_option('display.max_columns', None)

In [2]:
#loading in train data

default_na = 0

#list of providers
train = pd.read_csv('Train-1542865627584.csv')

#contains beneficiary KYC details like health conditions, region they belong to
train_bene = pd.read_csv('Train_Beneficiarydata-1542865627584.csv').fillna(default_na)

#provides insights about the claims filed for those patients who are admitted in the hospitals
train_inpatient = pd.read_csv('Train_Inpatientdata-1542865627584.csv').fillna(default_na)

#provides details about the claims filed for those patients who visit hospitals and not admitted in it
train_outpatient = pd.read_csv('Train_Outpatientdata-1542865627584.csv').fillna(default_na)

In [3]:
#loading in test data

test = pd.read_csv('Test-1542969243754.csv')
test_bene = pd.read_csv('Test_Beneficiarydata-1542969243754.csv').fillna(default_na)
test_inpatient = pd.read_csv('Test_Inpatientdata-1542969243754.csv').fillna(default_na)
test_outpatient = pd.read_csv('Test_Outpatientdata-1542969243754.csv').fillna(default_na)

In [4]:
train_benecln = train_bene[['IPAnnualReimbursementAmt','OPAnnualReimbursementAmt']][train_bene[['IPAnnualReimbursementAmt','OPAnnualReimbursementAmt']] >= 0].fillna(value = {'IPAnnualReimbursementAmt': train_bene['IPAnnualReimbursementAmt'].mean(),'OPAnnualReimbursementAmt': train_bene['OPAnnualReimbursementAmt'].mean()})
train_bene['IPAnnualReimbursementAmt'] = train_benecln['IPAnnualReimbursementAmt']
train_bene['OPAnnualReimbursementAmt'] = train_benecln['OPAnnualReimbursementAmt']
train_bene.describe()

,Gender,Race,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
count,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000
mean,1.570932,1.254511,25.666734,374.424745,11.907727,11.910145,1.667817,1.506322,1.687643,1.880041,1.762847,1.644476,1.398142,1.324143,1.725317,1.743180,1.920942,3660.837966,399.847296,1298.335104,377.718258
std,0.494945,0.717007,15.223443,266.277581,1.032332,0.936893,0.470998,0.499962,0.463456,0.324914,0.425339,0.478674,0.489517,0.468056,0.446356,0.436881,0.269831,9568.483958,956.175202,2493.870104,645.530187
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,11.000000,141.000000,12.000000,12.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,170.000000,40.000000
50%,2.000000,1.000000,25.000000,340.000000,12.000000,12.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,2.000000,0.000000,0.000000,570.000000,170.000000
75%,2.000000,1.000000,39.000000,570.000000,12.000000,12.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2300.000000,1068.000000,1500.000000,460.000000
max,2.000000,5.000000,54.000000,999.000000,12.000000,12.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,161470.000000,38272.000000,102960.000000,13840.000000

In [5]:
train_inpatient['In/Out'] = 'In'
train_outpatient['In/Out'] = 'Out'

In [6]:
train_temp = pd.concat([train_inpatient,train_outpatient], ignore_index = True)
train_temp

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,In/Out
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,0,0,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,0,0.0,0.0,0.0,0.0,0.0,0.0,In
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,0,2009-08-31,6186,1068.0,2009-09-02,750,6186,2948,56400,0,0,0,0,0,0,0,7092.0,0.0,0.0,0.0,0.0,0.0,In
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,0,PHY324689,2009-09-17,29590,1068.0,2009-09-20,883,29623,30390,71690,34590,V1581,32723,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,In
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,431,1068.0,2009-02-22,067,43491,2762,7843,32723,V1041,4254,25062,40390,4019,0,331.0,0.0,0.0,0.0,0.0,0.0,In
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,0,2009-08-13,78321,1068.0,2009-08-30,975,042,3051,34400,5856,42732,486,5119,29620,20300,0,3893.0,0.0,0.0,0.0,0.0,0.0,In
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558206,BENE159198,CLM510792,2009-08-06,2009-08-06,PRV53699,800,PHY364188,PHY364188,PHY385752,NaN,0,0.0,NaN,NaN,2163,V4575,53190,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Out
558207,BENE159198,CLM551294,2009-08-29,2009-08-29,PRV53702,400,PHY423019,PHY332284,0,NaN,0,0.0,NaN,NaN,07041,5781,25000,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Out
558208,BENE159198,CLM596444,2009-09-24,2009-09-24,PRV53676,60,PHY361063,0,0,NaN,0,0.0,NaN,NaN,V570,78079,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Out
558209,BENE159198,CLM636992,2009-10-18,2009-10-18,PRV53689,70,PHY403198,0,PHY419379,NaN,0,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Out
558210,BENE159198,CLM686139,2009-11-17,2009-11-18,PRV53689,80,PHY419379,0,PHY419379,NaN,0,0.0,NaN,NaN,78900,78609,4280,71946,3310,75311,2724,V103,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Out

In [7]:
#Create Age column to the dataset --not working (yet) a lot of DOD is None so difficult
from datetime import timedelta

#(pd.to_datetime(trn_df['ClaimStartDt'],format='%Y-%m-%d') - pd.to_datetime(trn_df['DOB'],format='%Y-%m-%d'))/timedelta(days=365)

train_bene['DOB'] = pd.to_datetime(train_bene['DOB'] , format = '%Y-%m-%d')
train_bene['DOD'] = pd.to_datetime(train_bene['DOD'],format = '%Y-%m-%d',errors='ignore')
#train_bene['Age'] = round((train_bene['DOD'] - train_bene['DOB'])/timedelta(days=365))

test_bene['DOB'] = pd.to_datetime(test_bene['DOB'] , format = '%Y-%m-%d')
test_bene['DOD'] = pd.to_datetime(test_bene['DOD'],format = '%Y-%m-%d',errors='ignore')
# test_bene['Age'] = round((test_bene['DOD'] - test_bene['DOB'])/timedelta(days=365))

In [8]:
train_df = pd.merge(pd.merge(train_temp, train, how='inner', on=['Provider']),train_bene, how='inner', on=['BeneID'])

In [9]:
train_df['Age_at_Claim'] = (pd.to_datetime(train_df['ClaimStartDt'],format='%Y-%m-%d') - pd.to_datetime(train_df['DOB'],format='%Y-%m-%d'))/timedelta(days=365)

In [10]:
# train_df.set_index(['Provider','In/Out','BeneID'],inplace=True)
# train_df.sort_values(['Provider','In/Out','BeneID'],inplace=True)

In [11]:
#ClmProcedureCode_3, 4, 5, and 6 have a lot of None values --might be worth ridding these columns?

In [12]:
#dependent variables
labels = train_df['PotentialFraud']

In [14]:
train_df['Provider'] = train_df['Provider'].apply(lambda s: s.split('PRV')[1])

IndexError: list index out of range

In [15]:
#not working (yet) trying to strip leading numbers from front of diagnosis codes
train_df['ClmDiagnosisCode_1'] = train_df['ClmDiagnosisCode_1'].apply(lambda t: t.split('V')[0])

AttributeError: 'int' object has no attribute 'split'

In [19]:
#Is this turning everything into a 1? regardless of the if condition?
train_df['In/Out'] = train_df['In/Out'].apply(lambda x: 1 if "In" else 0)

In [20]:
train_df

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,In/Out,PotentialFraud,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,Age_at_Claim
0,BENE11001,CLM46614,2009-04-12,2009-04-18,55912,26000,PHY390922,0,0,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,0,0.0,0.0,0.0,0.0,0.0,0.0,1,Yes,1943-01-01,1970-01-01,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000.0,3204,60.0,70,66.323288
1,BENE11001,CLM66048,2009-08-31,2009-09-02,55907,5000,PHY318495,PHY318495,0,2009-08-31,6186,1068.0,2009-09-02,750,6186,2948,56400,0,0,0,0,0,0,0,7092.0,0.0,0.0,0.0,0.0,0.0,1,No,1943-01-01,1970-01-01,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000.0,3204,60.0,70,66.709589
2,BENE11001,CLM68358,2009-09-17,2009-09-20,56046,5000,PHY372395,0,PHY324689,2009-09-17,29590,1068.0,2009-09-20,883,29623,30390,71690,34590,V1581,32723,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1943-01-01,1970-01-01,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000.0,3204,60.0,70,66.756164
3,BENE17521,CLM34721,2009-01-20,2009-02-01,55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,0,7769.0,5849.0,0.0,0.0,0.0,0.0,1,Yes,1913-12-01,1970-01-01,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000.0,1068,100.0,20,95.202740
4,BENE17521,CLM119066,2009-01-04,2009-01-04,55950,100,PHY311794,0,PHY394035,NaN,0,0.0,NaN,NaN,4919,1629,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1913-12-01,1970-01-01,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000.0,1068,100.0,20,95.158904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558206,BENE137034,CLM709479,2009-12-01,2009-12-01,51666,50,PHY312943,0,PHY397347,NaN,0,0.0,NaN,NaN,4404,44022,V707,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1960-12-01,1970-01-01,2,1,0,5,400,12,12,2,2,2,2,2,2,2,2,2,2,2,0.0,0,50.0,100,49.032877
558207,BENE137593,CLM685197,2009-11-16,2009-11-16,55089,400,PHY429922,0,PHY429922,NaN,0,0.0,NaN,NaN,5270,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1929-02-01,1970-01-01,1,1,0,33,540,12,12,2,2,2,2,2,2,2,2,2,2,2,0.0,0,400.0,600,80.843836
558208,BENE138363,CLM359448,2009-05-14,2009-05-14,52754,10,PHY354941,0,0,NaN,0,0.0,NaN,NaN,2724,462,25000,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1931-01-01,1970-01-01,2,1,0,14,141,12,12,2,2,2,2,2,2,2,2,2,2,2,0.0,0,10.0,0,78.419178
558209,BENE157238,CLM119946,2009-01-04,2009-01-04,55744,70,PHY319713,0,0,NaN,0,0.0,NaN,NaN,V292,42731,49390,V053,4011,7242,V0382,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1935-06-01,1970-01-01,2,1,0,37,250,12,12,2,1,2,2,2,2,2,2,2,2,2,0.0,0,70.0,0,73.646575
558210,BENE153476,CLM223803,2009-03-02,2009-03-02,52794,30,PHY365487,0,PHY365487,NaN,0,0.0,NaN,NaN,2723,2449,7906,78609,V5869,4019,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,No,1943-11-01,1970-01-01,1,1,0,14,820,12,12,2,2,2,2,2,1,2,1,2,2,2,0.0,0,30.0,0,65.378082

In [21]:
#independent variables 
features = ['Provider', 'In/Out', 'InscClaimAmtReimbursed', 'DeductibleAmtPaid', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmProcedureCode_1', 'ClmProcedureCode_2', 'DOB', 'Age_at_Claim']
features

['Provider',
 'In/Out',
 'InscClaimAmtReimbursed',
 'DeductibleAmtPaid',
 'ClmDiagnosisCode_2',
 'ClmProcedureCode_1',
 'ClmProcedureCode_2',
 'DOB',
 'Age_at_Claim']

In [22]:
X = train_df.reindex(columns=features)
X

,Provider,In/Out,InscClaimAmtReimbursed,DeductibleAmtPaid,ClmDiagnosisCode_2,ClmProcedureCode_1,ClmProcedureCode_2,DOB,Age_at_Claim
0,55912,1,26000,1068.0,4019,0.0,0.0,1943-01-01,66.323288
1,55907,1,5000,1068.0,2948,7092.0,0.0,1943-01-01,66.709589
2,56046,1,5000,1068.0,30390,0.0,0.0,1943-01-01,66.756164
3,55912,1,19000,1068.0,2639,7769.0,5849.0,1913-12-01,95.202740
4,55950,1,100,0.0,1629,0.0,0.0,1913-12-01,95.158904
...,...,...,...,...,...,...,...,...,...
558206,51666,1,50,0.0,44022,0.0,0.0,1960-12-01,49.032877
558207,55089,1,400,0.0,0,0.0,0.0,1929-02-01,80.843836
558208,52754,1,10,0.0,462,0.0,0.0,1931-01-01,78.419178
558209,55744,1,70,0.0,42731,0.0,0.0,1935-06-01,73.646575
558210,52794,1,30,0.0,2449,0.0,0.0,1943-11-01,65.378082

In [23]:
#setup plot for the confusion matrix and decision tree
import matplotlib.pyplot as plt
print(plt.rcParams.get('figure.figsize'))

[6.0, 4.0]

In [24]:
#setup figure size
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 20
fig_size[1] = 20
plt.rcParams["figure.figsize"] = fig_size

In [25]:
Y = train_df['PotentialFraud']

In [26]:
#some system checks for versions
from platform import python_version
print(python_version())
import sklearn

3.6.10

In [27]:
#import decision tree
print('The scikit-learn version is {}.'.format(sklearn.__version__))
from sklearn import tree

clf = tree.DecisionTreeClassifier(random_state=0)

##Cant have any chracters in these fields, must be numbers
clf = clf.fit(X, Y)

The scikit-learn version is 0.22.1.

ValueError: could not convert string to float: 'V5811'